### ISSUE TITLE
Issues on mobile devices - links and drag&drop not working

### ISSUE THREAD

**Issue by nmihin** [rhwilr/vue-nestable#100]
I added "delete" and "edit" actions inside VueNestableHandle and it works fine on desktop. The problem is on native devices, there is only a drag and drop option and I cannot click on my "delete" and "edit" buttons. Also, the drag option gets permanently stuck and I need to tap again to release the drag when using "cross-list" and group="cross" options. 

Check out the video of this issue on the link: https://www.youtube.com/watch?v=PmbgKfceknQ&feature

...or the screenshots in the attachment

![screen_1](https://user-images.githubusercontent.com/5212114/99240522-e6104580-27fc-11eb-9b8e-8d9b7aabe65b.jpg)
![screen_2](https://user-images.githubusercontent.com/5212114/99240523-e6a8dc00-27fc-11eb-954e-35bbde3a5d5f.jpg)

**Comment by rhwilr** [comment]
This looks to me like you need to stop the touch event from propagating when clicking the button. Have you tried adding the `.stop` modifier to the event listener?

**Comment by dallinbjohnson** [comment]
I am having the same problem on mobile and I have tried both .prevent .stop for @click on the icons.

**Comment by rhwilr** [comment]
I'll need more information in order to assess if this is a problem with `vue-nestable`.

- Does it work on the [demo page](https://rhwilr.github.io/vue-nestable/)?
- Can you link the source to your component or create a simple reproduction case? 
- Which mobile OS, Browser..?

**Comment by rhwilr** [comment]
You could also try to listen for the `touchstart` event instead of `click`.

**Comment by dallinbjohnson** [comment]
<iframe src="https://codesandbox.io/embed/gracious-dew-h9v9j?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="gracious-dew-h9v9j"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by dallinbjohnson** [comment]
@rhwilr  So you will have to inspect the page and use the mobile mode to get the errors. https://codesandbox.io/s/gracious-dew-h9v9j?file=/src/pages/Index.vue

**Comment by rhwilr** [comment]
If you use `@touchstart.stop="edit(scope.item)"` it works. I don't think there is anything wrong with `vue-nestable`. You just have to make sure to handle your touch events for mobile.

**Comment by dallinbjohnson** [comment]
I get errors in the console on mobile when dragging between list groups.

**Comment by dallinbjohnson** [comment]
> If you use `@touchstart.stop="edit(scope.item)"` it works. I don't think there is anything wrong with `vue-nestable`. You just have to make sure to handle your touch events for mobile.

Thanks I will start using `@touchstart.stop="edit(scope.item)`

**Comment by dallinbjohnson** [comment]
@rhwilr I get errors in the console on mobile when dragging between list groups.

```javascript
client-hook-6.js:1 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'getBoundingClientRect' of null"

found in

---> <VueNestableHandle>
       <NestableItem>
         <VueNestable>
           <DraggableTree> at src/pages/draggableTree.vue
             <QPage>
               <PageIndex> at src/pages/Index.vue
                 <QPageContainer>
                   <QLayout>
                     <MyLayout> at src/layouts/MyLayout.vue
                       <App> at src/App.vue
                         <Root>
```
