### ISSUE TITLE
Not dragging the examples without Drag handle on Mobile

### ISSUE THREAD

**Issue by jaronwanderley** [rhwilr/vue-nestable#109]
I tried to use the [examples](https://rhwilr.github.io/vue-nestable/) **on mobile** and get the error below:
`[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

How to reproduce:
- Open Goggle Chrome
- Open Inspector (ctrl + shift + i)
- Toggle to touch device (ctrl + shift + m)
- Try to drag any example whithout drag handle

**Comment by rhwilr** [comment]
This seems to only apply to the Chrome Dev Tools and is not an issue no a real mobile device.

**Comment by jaronwanderley** [comment]
@rhwilr But did you tried on mobile?
on my Android still not working...only the example with handles work... and kind of...
I showed a way of reproducing it on chrome... but on mobile isnt working too!
for reference Im using Chrome `92.0.4515.131 on android 10 QKQ1.190828.002`
