### ISSUE TITLE
Class to group

### ISSUE THREAD

**Issue by Krato** [rhwilr/vue-nestable#11]
Hello, first thanks for your awesome plugin.

Second, my problem. I want to add a class to the `.nestable-item` item. But seems imposible. 

The reason: I want to set a disabled class to the item. So all his childrens should be also disabled. I can set the class to this item, but no to his childrens.

How can achieve that?

I created a codesandbox to test it: https://codesandbox.io/s/6lyj1om093

Thanks

**Comment by rhwilr** [comment]
Thanks, glad you like it.
I think I can help you out here: I added a `classProp` that lets you define a property on the item object. This property will then be bound to the `li` of that item. This is available in [1.1.0-beta.2](https://github.com/rhwilr/vue-nestable/releases/tag/1.1.0-beta.2), If there are no issues, I will probably release 1.1.0 later this week.

Also, you can see this in action in the "Advanced" Demo: https://rhwilr.github.io/vue-nestable/

Hope this solves your problem.

**Comment by Krato** [comment]
Thanks to add this option. But something wrong is happening.

Check the example: https://codesandbox.io/s/6lyj1om093

<img width="720" alt="captura de pantalla 2019-01-05 a las 11 00 26" src="https://user-images.githubusercontent.com/74367/50723091-3a165300-10d9-11e9-92af-19dd507f2c25.png">

As you can see also in the image, there are spaces between the letters.

**Comment by rhwilr** [comment]
@Krato Thanks for this bug report. Strangely enough, I could only reproduce this in CodeSandbox but not in my compiled setup.
Anyway, It should be fixed in [1.1.0-beta.3](https://github.com/rhwilr/vue-nestable/releases/tag/1.1.0-beta.3).

**Comment by Krato** [comment]
Perfect mate! 👍🏽

**Comment by Krato** [comment]
@rhwilr https://packagist.org/packages/infinety-es/nova-menu-builder

**Comment by rhwilr** [comment]
Oh a Laravel Nova plugin, nice work @Krato! :+1: 
Now I will definitely have to check out Nova :smiley:
