### ISSUE TITLE
How to add collapsible groups for each nestable item with sub items

### ISSUE THREAD

**Issue by logicminds** [rhwilr/vue-nestable#116]
Given the code which is from the advanced example.   How can I add a toggle to expand/contract the nestable items.

<img width="380" alt="Screen Shot 2021-08-03 at 7 16 26 PM" src="https://user-images.githubusercontent.com/563900/128111258-711b81bc-7829-4376-8a74-e70eb0acae44.png">

```

<template>

  <div>
    <VueNestable
      v-model="nestableItems"
      :max-depth="4"
      :hooks="{'beforeMove': beforeMove}"
      key-prop="key"
      children-prop="nested"
      class-prop="class">

      <template slot-scope="{ item }">
        <!-- Handler -->
        <VueNestableHandle :item="item">
          <i class="material-icons drag_indicator" />
        </VueNestableHandle>

        <!-- Content -->

        <span>{{ item.text }}</span>
      </template>
    </VueNestable>
  </div>
</template>
```

**Comment by rhwilr** [comment]
This is not something that is handled by vue-nestable. You have to implement this on your side by tracking the state and render the only expanded items.

**Comment by logicminds** [comment]
I see a lot of collapse references in the code base so I thought it might be available.  Thanks for the awesome work on this component.
