### ISSUE TITLE
Disable area within slot

### ISSUE THREAD

**Issue by ainsleyclark** [rhwilr/vue-nestable#118]
Thank you for the great package.

I'm just wondering how to disable the dragging on a particular area off the draggable element.
For example, I don't want to user to be able to drag the H2, only the H1.

```html
<vue-nestable-handle slot-scope="{ item }" :item="item">
	<h1>Hello</h1>
	<h2>No Drag</h2>
</vue-nestable-handle>
```

Hope that makes sense and thank you in advance.

**Comment by rhwilr** [comment]
Try setting `pointer-events: none;` on the h2 element.

**Comment by ainsleyclark** [comment]
I've already tried that, not sure if there is an alternative?

Many thanks.

**Comment by rhwilr** [comment]
This depends on your usage. Another option could be to catch the [events the handle listenes to](https://github.com/rhwilr/vue-nestable/blob/master/src/VueNestableHandle.vue#L5) and prevent propagation.

There is no special property in the library to do this.
