### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by stepanenko3** [rhwilr/vue-nestable#127]
Do you have plans to upgrade to Vue3 or is the repository abandoned?

**Comment by rhwilr** [comment]
It is not abandoned. I'm using it with vue 2 in active projects.

At this moment I can not support vue 3. Please see the [readme](https://github.com/rhwilr/vue-nestable/blob/master/README.md?plain=1#L15) and https://github.com/rhwilr/vue-nestable/issues/96#issuecomment-1057132268
