### ISSUE TITLE
how create dynamic nestableItems

### ISSUE THREAD

**Issue by silverboy66000** [rhwilr/vue-nestable#128]
hi 
my nestableItems items get from DB 
so i call data from api 

how can i get items in nestableItems with for-loop

thanks

` <td v-for="(countriesZoneDataInfo ,index) in countriesZoneData " :key="key" style="vertical-align:top;direction:ltr!important;">
                            <div class="side">
                                <VueNestable v-model="nestableItems1[index+1]" cross-list group="cross" v-on:change="UpdateZone(nestableItems,countriesZoneDataInfo.id)">
                                    <div slot="placeholder">
                                        <b>This list is empty</b>
                                        <b>You Can drop down Some Country</b>
                                    </div>
                                    <VueNestableHandle slot-scope="{ item }" :item="item">
                                        <button type="button" class="btn btn-outline-primary btn-sm col-md-12">
                                            <i class="flaticon-049-copy"></i>{{ item.name }}{{ index+1 }}
                                        </button>
                                    </VueNestableHandle>
                                </VueNestable>
                            </div>
                        </td>`

**Comment by rhwilr** [comment]
See the first example in the Readme. It renders a list of items based on an array. In your case, the array would somehow come from the DB.
