### ISSUE TITLE
cannot use on vue 3 with vite 

### ISSUE THREAD

**Issue by satis-apex** [rhwilr/vue-nestable#129]
[vite] Internal server error: Failed to resolve entry for package "vue-nestable". The package may have incorrect main/module/exports specified in its package.json.  Plugin: vite:import-analysis

**Comment by rhwilr** [comment]
This package is currently only compatible with Vue 2. Vue 3 compatibility may be added in the future, though there are currently no plans for it.

**Comment by ryanrapini** [comment]
Bumping this in case anyone finds it through google like i did. I have provided a pull request #132 

You can also consume my fork of this which does nothing except update the package to support vite

@ryanrapini/vue-nestable

In my package.json I did:
```
"vue-nestable": "github:ryanrapini/vue-nestable",
```

**This won't work with Vue3 though probably, Vue2 only.**
