### ISSUE TITLE
onDrop event

### ISSUE THREAD

**Issue by sushant12** [rhwilr/vue-nestable#14]
Is there a way to trigger a method when an object is dropped? The `@input` event triggers every time I pick and drop an object. 

After an object is dropped, I just want to pass the `menus` array of objects back to the server.

```
<VueNestable
      v-model="menus"
      :max-depth="2"
      key-prop="position"
      children-prop="nested"
      @input="updateMenu"
    >
```

**Comment by rhwilr** [comment]
You can use the `change` event. 
I just noticed it is missing in the documentation :grimacing:
There is also a [PR](#13) open that will expose more information in the change event.

**Comment by sushant12** [comment]
let me try that

**Comment by sushant12** [comment]
nevermind, I misspelled chage while use @chage so i used :change which was so wrong.

**Comment by notflip** [comment]
Would it be possible to have access to all elements onChange? Like the input handler provides?

**Comment by rhwilr** [comment]
Yes. I would accept a PR that adds `items` as an additional option in the [change event](https://github.com/iceflash/vue-nestable/blob/master/src/VueNestable.vue#L464).
