### ISSUE TITLE
Improve drag'n'drop on mobile if items are not of equal size

### ISSUE THREAD

**Issue by rhwilr** [rhwilr/vue-nestable#15]
Draggin Items of different size causes the list to jump around. The fix that was used to make this work on desktop does not work on mobile since we are relying on mouse-move events.

We may need a completely different method to track movement that works on the desktop and on mobile.

Feedback and PRs are welcomed.

**Comment by Espumisan** [comment]
Hey!

After update to 2.2.0 this issue still appears! 

video: https://www.screencast.com/t/cEMeHNO8HW

Thanks!

**Comment by rhwilr** [comment]
@Espumisan Can you please upload the screencast to a site that does not require Flash?

**Comment by Espumisan** [comment]
I'm using [JING](https://www.techsmith.com/jing-tool.html), unfortunately it provides only flash, but you can enable it in google chrome! 

Maybe you know other software I can use?

**Comment by rhwilr** [comment]
That used to be the case, but it seems to no longer work. I'm not installing Flash.

The best way to report a bug is to create a Codesandbox using this template: https://codesandbox.io/s/pk3923rwz0

**Comment by Espumisan** [comment]
Hey! I have complex components inside project already, I made a new Video:
https://www.dropbox.com/s/7rld44ol3l7w68c/20190312_091639.mp4?dl=0

You can see it is sitll jumping, and you can't add smaller to bigger from the top, take a look mate :)

**Comment by rhwilr** [comment]
The reason I asked for a CodeSandbox is so a can reproduce the issue to find the bug.
Also, it could be the case that this issue only applies to your use-case and might be a CSS issue or a component inside the nestable-item. By creating a simple example to reproduce the issue, we can make sure that it is a general issue.

In any case, I don't have much free time to work on this in the next few weeks. If you depend on this being fixed, please consider submitting a PR.
