### ISSUE TITLE
Internet explorer 11 support

### ISSUE THREAD

**Issue by Espumisan** [rhwilr/vue-nestable#16]
When I test this plugin in IE 11 I get error `'Symbol' is undefined`, after inserting Symbol polyfill I get a new error:
`Unable to get property 'getBoundingClientRect' of undefined or null reference`

Is it possible to make this work in IE11, because it's our requirement in project i'm working on

**Comment by rhwilr** [comment]
I don't support IE 11 in my projects. But I will happily accept a PR for this.

**Comment by rhwilr** [comment]
I spent a few minutes looking into this. I think you need to import a polyfill for
`Element.prototype.matches` and `Element.prototype.closest`.
I added polyfill.io on the demo site and it seems to work with the following config polyfills:
[https://polyfill.io/v3/polyfill.js?features=es5,es6,default,Element.prototype.matches,Element.prototype.closest&flags=gated](https://polyfill.io/v3/polyfill.js?features=es5,es6,default,Element.prototype.matches,Element.prototype.closest&flags=gated)
