### ISSUE TITLE
error on drag

### ISSUE THREAD

**Issue by pstaabp** [rhwilr/vue-nestable#18]
Just started using this and got the following error:
```
vue.runtime.esm.js?2b0e:1887 DOMException: Failed to execute 'querySelector' on 'Document': '.nestable-15lajd6o315 .nestable-item-HW_02:answer' is not a valid selector.
    at VueComponent.listStyles (webpack-internal:///./node_modules/vue-nestable/dist/vue-nestable.es.js:708:25)
```
Note: using webpack, so not sure the line numbers are accurate. 

I found the problem.  I used a colon : in the id of the list item.  which isn't valid for a classname.  Perhaps you can throw an error if the id doesn't have the proper form.

**Comment by rhwilr** [comment]
I added a note in the docs.
