### ISSUE TITLE
Possible to have the VueNestableHandle in a child component?

### ISSUE THREAD

**Issue by notflip** [rhwilr/vue-nestable#19]
I'm trying to add the VueNestableHandle into a child component, but as expected I get the following error

`Failed to execute 'querySelector' on 'Document': '.nestable-q6putfiw0pk .nestable-item-[object Object]' is not a valid selector.
`

Since it can't find the parent, I'm guessing.
Is there anyway this is possible?

**Comment by rhwilr** [comment]
The `.nestable-item-[object Object]` tells me that you are not setting the `keyProp` correctly. You have to provide a string property that uniquely identifies your items.
By default, it will look for a property called `id`. If this does not exist on your model and is called differently, you will have to set the `keyProp` prop.

**Comment by notflip** [comment]
Aha, got it working. Thanks! Great plugin, thanks for your work and time on this
