### ISSUE TITLE
Issue with dragging and reordering

### ISSUE THREAD

**Issue by notflip** [rhwilr/vue-nestable#21]
I've got some strange behaviour, as you can see I have elements, Alfa, Bravo, Charlie.
When I reorder, strange things are happening, I recorded the behaviour
http://g.recordit.co/el35fPe1l1.gif

Any idea what might be causing this?

**Comment by notflip** [comment]
I made another recording, there's also an error now, 
http://recordit.co/gSdwRy4Grj/gif/notify

![Screenshot 2019-03-14 at 15 15 38](https://user-images.githubusercontent.com/4146384/54363839-0a04a680-466c-11e9-94f4-0bbead1e8efa.png)

**Comment by notflip** [comment]
I'm looking further into this, It appears to go wrong from **the moment I select an item and start dragging.**

http://recordit.co/pSD9a18vZW/gif/notify

**Comment by rhwilr** [comment]
Without an actual source-code example, I can only guess. I'd check that your `keyPro` is actually unique.

**Comment by notflip** [comment]
You're right, was a keyProp issue. Thanks for this!
