### ISSUE TITLE
pathTo returns null once in a while

### ISSUE THREAD

**Issue by notflip** [rhwilr/vue-nestable#22]
There's a small issue where sometimes, the pathTo returns **undefined**, it happens a very short while after releasing an item.

### Steps to reproduce
I drag the first item (item 0) to the last position (3), it doesn't always happen and when it does, It happens a second or so after releasing. These are the details

_console.log screenshot_
![Screenshot 2019-03-15 at 09 17 58](https://user-images.githubusercontent.com/4146384/54417775-6bc41f80-4703-11e9-859e-681f161d8d14.png)

_console.log code block_
![Screenshot 2019-03-15 at 09 18 05](https://user-images.githubusercontent.com/4146384/54417783-6f57a680-4703-11e9-82b0-101846270be1.png)

_undefined pathTo_
![Screenshot 2019-03-15 at 09 19 15](https://user-images.githubusercontent.com/4146384/54417792-72eb2d80-4703-11e9-9f42-d10d44940c8c.png)

**Comment by rhwilr** [comment]
This is now fixed in version [2.3.2](https://github.com/rhwilr/vue-nestable/releases/tag/2.3.2)
Thanks for reporting this bug and please excuse the slow response.
