### ISSUE TITLE
Creating a new item, dragging a parent makes it disappear

### ISSUE THREAD

**Issue by notflip** [rhwilr/vue-nestable#23]
Is there anything that needs to happen for the data to stay in sync?
**It seems like the dragItem doesn't include the new child I created when I start dragging**

http://g.recordit.co/Welrvs5Kf0.gif

My App data seems to be in sync with the VueNestable data (see screenshots)

![Screenshot 2019-03-27 at 09 41 10](https://user-images.githubusercontent.com/4146384/55061646-89cf3f80-5074-11e9-8b76-352f01430d58.png)

![Screenshot 2019-03-27 at 09 41 18](https://user-images.githubusercontent.com/4146384/55061649-8cca3000-5074-11e9-91e2-9083bad71578.png)

**Comment by rhwilr** [comment]
If you use `v-model` it should work.
Can you share code?
