### ISSUE TITLE
Very small issue in Documention

### ISSUE THREAD

**Issue by jdriesen** [rhwilr/vue-nestable#3]
Hi @rhwilr 

First of all... CONGRATZ with this component !
Really a great piece of software.

I just want to mention a very minor issue in the documentation on https://rhwilr.github.io/vue-nestable/
The "link to code" button of the "Draggable across different lists" example, is pointing to "https://github.com/rhwilr/vue-nestable/blob/master/docs/src/components/Advanced.vue"

(I guess this has to be a link to "https://github.com/rhwilr/vue-nestable/blob/master/docs/src/components/CrossList.vue" ....)

Grtz,
Johnny

**Comment by rhwilr** [comment]
You're welcome, glad you like it :smiley: 
The link is now fixed.
