### ISSUE TITLE
How do you render this array? 

### ISSUE THREAD

**Issue by Arc-zlz** [rhwilr/vue-nestable#60]
let array = [{
    type:1,
    name:"tom"
},{
    type:2,
    age:18
},{
    type:3,
    sex:"man"
}]

**Comment by Arc-zlz** [comment]
What I'm thinking about now is whether there's a better way to do this.
<vue-nestable v-model="array" :maxDepth="number" keyProp="type" childrenProp="" group="cross">
            <vue-nestable-handle
                slot-scope="{ item }"
                :item="item"
                v-show="item !== 0"
            >
                {{ item }}
            </vue-nestable-handle>
        </vue-nestable>
        <vue-nestable v-model="array" :maxDepth="number" keyProp="type" childrenProp="" group="cross">
            <vue-nestable-handle
                slot-scope="{ item }"
                :item="item"
                v-show="item === 0"
            >
                {{ item }}
            </vue-nestable-handle>
        </vue-nestable>

**Comment by Arc-zlz** [comment]
```js
```

**Comment by Arc-zlz** [comment]
What I'm thinking about now is whether there's a better way to do this??
```js
<vue-nestable v-model="array" :maxDepth="number" keyProp="type" childrenProp="" group="cross">
            <vue-nestable-handle
                slot-scope="{ item }"
                :item="item"
                v-show="item !== 0"
            >
                {{ item }}
            </vue-nestable-handle>
        </vue-nestable>
        <vue-nestable v-model="array" :maxDepth="number" keyProp="type" childrenProp="" group="cross">
            <vue-nestable-handle
                slot-scope="{ item }"
                :item="item"
                v-show="item === 0"
            >
                {{ item }}
            </vue-nestable-handle>
        </vue-nestable>
```

**Comment by rhwilr** [comment]
What do you mean by better way? Can you explain what doesn‘t work for your usecase?

**Comment by Arc-zlz** [comment]
Thank you for your reply! This example is no problem, but not elegant enough. I want to ask you if you know there is a better way to implement it.

**Comment by rhwilr** [comment]
No, this is how the component currently works. But I'm always open for ideas on how we can improve the developer experience.

**Comment by Arc-zlz** [comment]
Um...I haven't thought of a good way to improve it for the time being. Ha ha ha ha ha, let me think again, thank you for your reply, go to bed first, we are different from your time difference.

**Comment by rhwilr** [comment]
No problem. I'm closing this issue for now. Feel free to open a new issue or PR though, for suggestions on improvements.
