### ISSUE TITLE
Emit mouseenter event

### ISSUE THREAD

**Issue by lapaliv** [rhwilr/vue-nestable#7]
Hello. In my tree, I have an opportunity to hide and to open some part of tree.
I haven't opportunity to open a hidden node on move other tree node.

Please add emit @mouseenter event for VueNestable component for it.

For example (video) https://yadi.sk/i/74FfrnOdwvIlcA

**Comment by rhwilr** [comment]
I'm not sure I understand. In your video, the collapsed node seems to open when you hover over it. So what exactly is not working?
Can you share the source to this? 

But I think you can already get a mouseenter event by binding it when you render the content:
```
  <vue-nestable v-model="nestableItems">
    <div
      slot-scope="{ item }"
      @mouseenter="handleMouseenter">
      {{ item.text }}
    </div>
  </vue-nestable>
```

**Comment by lapaliv** [comment]
> Can you share the source to this?

It's the other project to vue draggable (https://github.com/phphe/vue-draggable-nested-tree), but your project is more suitable for me

> But I think you can already get a mouseenter event by binding it when you render the content:

It's a good idea. Thanks
