### ISSUE TITLE
drag'n'drop on mobile device

### ISSUE THREAD

**Issue by iceflash** [rhwilr/vue-nestable#8]
Hi! Trying on mobile device, but it seems not working. Do you planing add support for mobile device?

**Comment by rhwilr** [comment]
Hi @iceflash
Mobile is currently not supported, but I am looking into it. It is certainly planned for the next release, but I can't yet say when it will ship.

**Comment by rhwilr** [comment]
I just worked on it a bit more.
You can check out [v1.1.0-beta.0](https://github.com/rhwilr/vue-nestable/releases/tag/1.1.0-beta.0) to test it on mobile.

**Comment by iceflash** [comment]
> 
> 
> I just worked on it a bit more.
> You can check out [v1.1.0-beta.0](https://github.com/rhwilr/vue-nestable/releases/tag/1.1.0-beta.0) to test it on mobile.

Hi! Thank you very much! I will try it, and reply/close issue
