### ISSUE TITLE
How temporally disable dragging?

### ISSUE THREAD

**Issue by Polimorf** [rhwilr/vue-nestable#80]
I want to disable and enable dragging when this need.. but I don't see any option for this.

**Comment by rhwilr** [comment]
If you don't use the `VueNestableHandle` component, items in the list won't be draggable. 
See the first example on the [demo page](https://rhwilr.github.io/vue-nestable/).

**Comment by Polimorf** [comment]
> If you don't use the `VueNestableHandle` component, items in the list won't be draggable.
> See the first example on the [demo page](https://rhwilr.github.io/vue-nestable/).

Yes, it worked! Thanks.
