### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by RoOhi-E** [rhwilr/vue-nestable#82]
Hi @rhwilr 
I wanna know do you have any plan to add rtl support?
thanks

**Comment by rhwilr** [comment]
No, I don't have any plans at the moment.
But the library only tracks the mouse position, that should not change as far as I know. There is no css or text that would dictate left-to-right.

Can you tell me what is missing for rtl support, as I don't have any experience with it?

**Comment by RoOhi-E** [comment]
Just some css changes & _diffX_ const rtl check :)
I made a pull request for rtl support #83

**Comment by rhwilr** [comment]
I took a look at your PR and it looks sensible. However, I don't have experience with RTL layouts, so if I make changes in the future, would you be open to take a look at it again and make sure I didn't break RTL support?

**Comment by RoOhi-E** [comment]
Yes, that's OK
