### ISSUE TITLE
How to set advanced group relation

### ISSUE THREAD

**Issue by mksc1123** [rhwilr/vue-nestable#84]
Hello Mr.Huwiler, @rhwilr

I'm Mizuki.
I want to know how to set advanced group relation.

For example, I have three cards, question card, answer card and scenario design card.
There are some blocks at question card and answer card.
I want to move a block from question to scenario design and from answer to scenario design.
But, I don't want to move a block from question to answer, and vice versa.

Can I control this moving with vue-nestable?

Thank you.

**Comment by rhwilr** [comment]
Hi @mksc1123 

Thank you for using vue-nestable! Take a look at [Hooks](https://github.com/rhwilr/vue-nestable#hooks), I think you should be able to implement your use-case using the `beforeMove` hook.

You can also check out the [Advanced](https://github.com/rhwilr/vue-nestable/blob/master/example/components/Advanced.vue) example, that should give you a hint how to use the hook.

Hope this helps.

**Comment by mksc1123** [comment]
Hi @rhwilr
Thank you for helping!

I'll try to use Hooks checking the Advanced example.
I do my best to implement with your advice.
Thank you!!
