### ISSUE TITLE
Drag and drop item position flickering

### ISSUE THREAD

**Issue by elvijs-teikmanis-emergn** [rhwilr/vue-nestable#87]
When item or handle is clicked then dragged item moves to top left corner and only then restores position under mouse pointer. Sometimes item locks at top left corner and after next move event position restores.

In order to reproduce go to: https://rhwilr.github.io/vue-nestable/

1) Click on red handle
2) Move slowly

**Comment by rhwilr** [comment]
Thank you for reporting this issue!
I just published version [2.5.1](https://github.com/rhwilr/vue-nestable/releases/tag/2.5.1) which addresses this issue.
