### ISSUE TITLE
Disable drag&drop for touch = tap/longtap events?

### ISSUE THREAD

**Issue by Arenukvern** [rhwilr/vue-nestable#89]
Hello.

I searched documentation, but cannot find a way to prevent drag event for touch devices.

For desktop - all works if simply to add attribute draggable = false.
But for touch devices it not working at all (ondragstart doesn't work also).

Could you help with the issue?
Thank you!

**Comment by rhwilr** [comment]
You can disable dragging by not rendering a `VueNestableHandle`. Take a look at the [List](https://github.com/rhwilr/vue-nestable/blob/master/example/components/Simple.vue) example.

**Comment by Arenukvern** [comment]
Thank you for your help! Solved with the principle [Advanced](https://github.com/rhwilr/vue-nestable/blob/master/example/components/Advanced.vue)
