### ISSUE TITLE
option pathTo incorrect data

### ISSUE THREAD

**Issue by alhavizd** [rhwilr/vue-nestable#90]
option pathTo incorrect data. when last item drag to top/first, then drag to child of first item data pathTo [1], should be [0, 0]. if that data, drag again to parent, but not first. after that drag again, pathTo correct
![Untitled Project](https://user-images.githubusercontent.com/23514820/77597691-3a934780-6f32-11ea-9fae-2f95af1faf99.gif)

**Comment by rhwilr** [comment]
Hi,
I tried to create a simple test case to reproduce this bug, but I'm unable to do so.
What am I missing? I create this Sandbox, so you can see for yourself: https://codesandbox.io/s/silly-cookies-35eo7

**Comment by alhavizd** [comment]
Hi, I tried your simple codesandbox. but still the same. I still have the same problem
![bugs](https://user-images.githubusercontent.com/23514820/77756403-a9bb8980-7061-11ea-8c23-d5af7553b4c6.gif)

**Comment by rhwilr** [comment]
Ah now I was able to reproduce it and I found the bug. I just tagged [v2.5.3](https://github.com/rhwilr/vue-nestable/releases/tag/2.5.3) to address this issue.

Thanks for reporting this issue.
