### ISSUE TITLE
Does it support for virtual scroll, otherwise this may suffer performance issues when there is larger data.

### ISSUE THREAD

**Issue by MaheshB0ngani** [rhwilr/vue-nestable#93]
Does it support for virtual scroll?
Do you have any plan to include virtual scroll?
I can contribute for this feature, if you need.

**Comment by rhwilr** [comment]
No, vue-nestable does not support a virtual scrollbar and I currently don't plane to support it.
I think this feature is outside the scope for vue-nestable. An external library may be able to provide this.

**Comment by ysk2014** [comment]
I have a performance problem now, when the nesting level is above 6
