### ISSUE TITLE
'non-droppable' property for handles

### ISSUE THREAD

**Issue by origami1024** [rhwilr/vue-nestable#95]
It would be cool property allowing creation of structures like filesystem - where you can drag&drop some handles but cant drop anything inside them (like files as opposed to folders).

**Comment by rhwilr** [comment]
You should be able to do this with the `beforeMove` hook. You'll get the item that was dragged and where it was dragged to. Then you should be able to check if it is a file and abort the drag action.

**Comment by origami1024** [comment]
Seems like beforeMove is good enough, thanks
